spring.application.name=ReceiptTracker

# Railway MySQL Database Connection
spring.datasource.url=jdbc:mysql://maglev.proxy.rlwy.net:57635/railway
spring.datasource.username=root
spring.datasource.password=VcYBwlYkoRYFgOOnxiEjlcabHAApHAEM
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# App
server.port=8080